name: build-template
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Replace this with your build commands
      - name: Build code
        run: |
          echo "Building code..."
