name: CI/CD Pipeline

on:

  workflow_dispatch:
jobs:
   build:

     runs-on: ubuntu-latest
     name: A job to say hello
     steps:
      - uses: actions/checkout@v3
      - uses: mule-pipeline/.github/workflows/jira-jobs.yml@main
        with:
          name: mahmoud


