name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name : ls
        run : ls
      - name : pwd
        run : pwd
      # Use the build job template from the same repository
      - name: Build code
        uses: ./.github/workflows/jobs/build-template
