name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Use the build job template from the same repository
      - name: Build code
        uses: ./.github/workflows/actions/build-template
