name: CI/CD Pipeline

on:

  workflow_dispatch:
jobs:
   build:

     runs-on: ubuntu-latest
     name: A job to say hello
     steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/jira-action/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

