name: CI/CD Pipeline

on:

  workflow_dispatch:
jobs:
  call-jira-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jira Action
        uses: ./.github/actions/jira-action
        with:
          name: 'World'
#   call-workflow-passing-data:
#     uses: ketatamahmoud/mule-pipeline/.github/workflows/jira-jobs.yaml@main
#     with:
#       config-path: .github/labeler.yml
#     secrets:
#       envPAT: ${{ secrets.envPAT }}
#   call-workflow-2-passing-data:
#     uses: /mule-pipeline/.github/workflows/jira-jobs.yaml@main
#     with:
#       config-path: .github/labeler.yml
#     secrets:
#       envPAT: ${{ secrets.envPAT }}
#   call-workflow-3-passing-data:
#       uses: ./.github/workflows/jira-jobs.yaml
#       with:
#         config-path: .github/labeler.yml
#       secrets:
#         envPAT: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-3-passing-data:
      uses: ./.github/workflows/test/workflow.yml
      with:
        config-path: .github/labeler.yml


