name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : ls
        run : ls -a
      - name : pwd
        run : pwd
      - name : cd
        run : cd .github/workflows/actions
      - name: ls 
        run : ls
      # Use the build job template from the same repository
      - name: Build code
        uses: ./.github/workflows/actions/build-template

