name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Use the build job template from the same repository
      - name: Build code
        uses: ./.github/actions/build-template
